<footer id="contact">
			<div class="container">
				<div class="row">
					<div class="col-md-4 footer-leftcol">
						<p><span class="bold-16p">QLD Brisbane</span><br>
						Shop 8/974 Waterworks Road<br>
						The Gap Street side of The Gap Village Shopping Center - 
						<br><a href="http://wecare.jcubitgroup.com/ICT%202%20WeCare/index.php">wecare@jcubitgroup.com</a>
						</p>
					</div>
					<div class="col-md-4 footer-midcol">
						<ul>
							<li><a href="https://twitter.com/We_Care_Massage" class="twitter-icon">Twitter</a></li>
							<li><a href="https://www.facebook.com/wecaremassage/" class="facebook-icon">Facebook</a></li>
							<li><a href="https://www.instagram.com/wecaremassage" class="pintrest-icon">Instagram</a></li>
						</ul>
						<div class="clearfix"></div>
					</div>
					<div class="col-md-4 footer-rightcol">
						<p>Designed by <a href="contactus.php">WeCareGroup</a></p>
					</div>
					<div>
						<audio src="img/bgm.mp3" autoplay>
							<embed src="img/bgm.mp3" width="180" height="90" hidden="false" />
						</audio>
					</div>
				</div>
			</div>
		</footer>