
	<div class="container">
		<div class="row">
			<a href="index.php"><div class="responsive-logo">
			</div></a>
			<div class="pullcontainer"> 
				<a href="#" id="pull"><i class="fa fa-bars fa-2x"></i></a>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8 col-md-offset-2 col-lg-offset-0 col-lg-12">
				<nav>
  					<ul class="clearfix">
		   				<li><a href="whyus.php">Why Us</a></li>
                    	<li class="dot">.</li>
                    	<li><a href="treatments.php">Treatments</a></li>
                    	<li class="dot">.</li>
						<li><a href="special.php" class="r_spacer">Prices</a></li>
						<a href="index.php"><div class="logo-holder"></div></a>
						<li><a href="book.php">Book Online</a></li>
						<li class="dot">.</li>
						<li><a href="login.php">Admin</a></li>
						<li class="dot">.</li>
						<li><a href="contactus.php">Contact Us</a></li>
					</ul>
				</nav>
			</div>
		</div>
	</div>

